Add support for Output Interface #123
pouriyajamshidi/tcping pull request #128
Opened 2023-08-13 13:22 UTC by AKARSHITJOSHI

Closes #123

2023-08-14 15:11 UTC, pouriyajamshidi requested changes

2023-08-14 15:11 UTC, pouriyajamshidi commented on tcping.go
> +
I would also move this way up the code base, ideally below the `processUserInput` fucntion

2023-08-14 15:11 UTC, pouriyajamshidi commented on tcping.go
> +	interfaceN := flag.String("i", "no-interface", "interface to dial the tcp connection")
```suggestion
	interfaceName := flag.String("i", "no-interface", "interface to use for TCP connections")
```

2023-08-21 14:47 UTC, AKARSHITJOSHI commented on tcping.go
> +		IPAndPort = netip.AddrPortFrom(IPAdress, tcpStats.userInput.port)
should I add a field netip.AddrPort to tcp.userInput ??

2023-08-22 07:54 UTC, pouriyajamshidi commented on tcping.go
> +		IPAndPort = netip.AddrPortFrom(IPAdress, tcpStats.userInput.port)
I would start with just the interface for now.

2023-08-25 19:21 UTC, closed without merging