Implement custom timeout value feature
pouriyajamshidi/tcping pull request #130
Opened 2023-08-14 09:00 UTC by luca-patrignani

# Important

**Please provide the requested parameters below to help us review your pull request.**

**Pull requests without a body or explanation will be rejected.**

## Describe your changes
Implement custom dial timeout feature
## Issue ticket number and link
#7
Closes #7

## Checklist before requesting a review

- [ ] I have performed a self-review of my code
- [ ] If it is a core feature, I have added tests.
- [ ] I have run `make check` and there are no failures.

## Type of change

Please delete options that are not relevant.

- [ ] New feature (non-breaking change which adds functionality)
- [ ] This change requires a documentation update

2023-08-14 09:11 UTC, pouriyajamshidi commented
Hi @luca-patrignani,

Thanks a lot for your contribution.

It seems like the CodeFactor does not like this line:

![image](https://github.com/pouriyajamshidi/tcping/assets/54482226/56f19d8b-809d-4c19-b357-f268f95a768e)


I will start reviewing this PR once CodeFactor is happy :)

2023-08-14 15:03 UTC, pouriyajamshidi commented
@luca-patrignani, I ran a few tests on my machine and noticed some inaccuracies in the time report. For instance running `go run ./... yahoo.com 443 -t 2` yields what is depicted in the image below:

![image](https://github.com/pouriyajamshidi/tcping/assets/54482226/5bcb1a36-f073-4da4-a225-8a25b0f6d411)


we can see `longest consecutive downtime` is wrong. It should be 10. 

Additionally, this part:

```console
TCPing started at: 2023-08-14 16:49:08
TCPing ended at:   2023-08-14 16:49:13
duration (HH:MM:SS): 00:00:10
```

shows the correct duration but `start` and `end` time are not adding up.


I thought this could be something that was already a problem in the code, but after a few checks on v2, I could confirm that the time display is working fine there.

2023-08-16 15:07 UTC, pouriyajamshidi commented
> Hi, I'm not able to reproduce the bug, can you help me? And sorry for this long PR review.

Hi @luca-patrignani,

First of all, thank you for willing to contribute to this project and your patience addressing my comments.

what you can run to get that result is:

```bash
go run ./... distrowatch.com 444 -c 4
```

Notice the port `444`. It is intentional to have probe failures to get that result.

There is no rush, take your time.

2023-08-16 18:42 UTC, luca-patrignani commented
Hi, I still can't reproduce the bug. This is the output of  `go run ./... distrowatch.com 444 -c 4`:
![image](https://github.com/pouriyajamshidi/tcping/assets/92518571/09dd295c-69ca-4538-ab64-2743e3a08751)
I ran this multiple times but the output always looked correct to me.

2023-08-16 19:12 UTC, pouriyajamshidi commented
> Hi, I still can't reproduce the bug. This is the output of `go run ./... distrowatch.com 444 -c 4`: ![image](https://user-images.githubusercontent.com/92518571/261103991-09dd295c-69ca-4538-ab64-2743e3a08751.png) I ran this multiple times but the output always looked correct to me.

Hi @luca-patrignani,

hmmm, maybe I tested it right before you pushed some changes.

Will test it again tomorrow when I am back.

Thanks again

2023-08-17 19:58 UTC, pouriyajamshidi requested changes
Hi @luca-patrignani,

Sorry for my late responses. There are a lot going on simultaneously :)

Overall your work looks good and quite clever.

I have added my remarks which are mostly concerning the time report.

In addition to those, there is one more detail that jumped out:

![image](https://github.com/pouriyajamshidi/tcping/assets/54482226/2f0c873d-95b2-464c-8fc1-b54b2c971064)

To reproduce, you can use:

```bash
sudo iptables -A OUTPUT -d 74.6.231.21 -j DROP; sleep 3; sudo iptables -F
```

Oddly, instead of moving on to the next probe, it shows 3 seconds in the one that has failed.

2023-08-17 19:58 UTC, pouriyajamshidi commented on tcping.go
> +		tcpStats.handleConnSuccess(rtt, connStart, maxDuration(connDuration, tcpStats.intervalBetweenProbes))
Let's extract this `maxDuration` outside this condition.

```go
elapsed :=  maxDuration(connDuration, tcpStats.intervalBetweenProbes)
```

Then we just pass it to our conditions

2023-08-17 19:58 UTC, pouriyajamshidi commented on tcping.go
> +		uptime := time.Since(tcpStats.startOfUptime).Truncate(time.Second)
I think `Truncate` is causing some very tiny "miscalculations".

Check out the `longest consecutive uptime` value in these two images:

![image](https://github.com/pouriyajamshidi/tcping/assets/54482226/2f1d1d25-a967-49aa-aeaf-d7d3209c975f)


And then:


![image](https://github.com/pouriyajamshidi/tcping/assets/54482226/238e604b-cb4d-4d9c-954f-fbac3a5e268c)


You have to run it a few times to reproduce but my guess is, if the connection duration falls under a certain value, it just truncates it.

2023-08-18 07:19 UTC, luca-patrignani commented
> Hi @luca-patrignani,
> 
> Sorry for my late responses. There are a lot going on simultaneously :)
> 
> Overall your work looks good and quite clever.
> 
> I have added my remarks which are mostly concerning the time report.
> 
> In addition to those, there is one more detail that jumped out:
> 
> ![image](https://user-images.githubusercontent.com/54482226/261422570-2f0c873d-95b2-464c-8fc1-b54b2c971064.png)
> 
> To reproduce, you can use:
> 
> ```shell
> sudo iptables -A OUTPUT -d 74.6.231.21 -j DROP; sleep 3; sudo iptables -F
> ```
> 
> Oddly, instead of moving on to the next probe, it shows 3 seconds in the one that has failed.

Hi, 
I am not entirely sure of what you would expect. The line should be "No response received for **2** seconds", right?

2023-08-18 08:43 UTC, luca-patrignani commented
Hi, 
I just pushed 4 commits, one for each points you made.

2023-08-18 15:35 UTC, pouriyajamshidi requested changes
Hey @luca-patrignani,

Everything looks good and this can get merged in when you address the final points.

2023-08-19 11:13 UTC, pouriyajamshidi approved these changes
Good job @luca-patrignani and thanks for your contribution!

Sorry for the extra scrutiny. Anything that touches time is subject to it.

2023-08-19 11:18 UTC, merged