Update process user input
pouriyajamshidi/tcping pull request #149
Opened 2023-09-15 13:35 UTC by friday963

# Important

**Please provide the requested parameters below to help us review your pull request.**

**Pull requests without a body or explanation will be rejected.**

Refactor updateuserinput func to consolidate logic and args setttings into smaller units of work.

## Issue ticket number and link

Closes #

## Checklist before requesting a review

- [x] I have performed a self-review of my code
- [ ] If it is a core feature, I have added tests.
- [x] I have run `make check` and there are no failures.

## Type of change

Please delete options that are not relevant.

N/A

2023-09-15 13:38 UTC, friday963 commented
Figured I'd just start the PR so you could see the diff.

2023-09-16 12:02 UTC, pouriyajamshidi requested changes
Hey @friday963,

Thanks for your contribution. It definitely looks much cleaner than before.

After my requested changes are in place, this can get merged in.

2023-09-16 15:34 UTC, friday963 commented on tcping.go
> +	} else if *ip6 {
Ok so split this into two methods.  One to check for both flags being true then print the error/usage if so, another to update the struct as a subsequent method right below?

func alertIPFlagConflict(){
if ip4 and 6
     printerror()
     useage()
}

func setIPFlags(){
if ip4
 useip4 = true
 if ip6
 useip6 = true
}

2023-09-16 15:34 UTC, friday963 commented on tcping.go
> +func checkUpdatePort(tcpstats *stats, args []string) {
Good catch

2023-09-16 15:48 UTC, pouriyajamshidi commented on tcping.go
> +	} else if *ip6 {
ah no, I meant to say those don't need to be `else if` just an `if` will do the trick.

2023-09-16 19:33 UTC, pouriyajamshidi approved these changes
Thanks @friday963!

2023-09-16 19:42 UTC, merged

2023-09-16 20:08 UTC, friday963 commented
My pleasure!